# Generated by Django 3.2 on 2021-04-16 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210416_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
